const express = require('express');
const dotenv = require('dotenv');
const { connectDB } = require('./db/connect');
const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;

const serverUrl = process.env.RENDER_EXTERNAL_URL || `http://localhost:${port}`;

app.use(express.json());

const swaggerOptions = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'Contact API',
      version: '1.0.0',
      description: 'API documentation for the Contact application',
    },
    servers: [
      {
        url: serverUrl,
      },
    ],
    components: {
      schemas: {
        Contact: {
          type: 'object',
          properties: {
            _id: { type: 'string', description: 'Contact ID (auto-generated by MongoDB)', example: '60564fcb5450ae0015b90570' },
            firstName: { type: 'string', description: "Contact's first name", example: 'John' },
            lastName: { type: 'string', description: "Contact's last name", example: 'Doe' },
            email: { type: 'string', description: "Contact's email address", example: 'john.doe@example.com' },
            favoriteColor: { type: 'string', description: "Contact's favorite color", example: 'Blue' },
            birthday: { type: 'string', format: 'date', description: "Contact's birthday", example: '1990-01-15' }
          },
          required: ['firstName', 'lastName', 'email'] // Example required fields
        }
      }
    }
  },
  apis: ['./routes/*.js'],
};

const swaggerDocs = swaggerJsdoc(swaggerOptions);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));

app.get('/', (req, res) => {
  res.send('CSE341 Contact API is running');
});

app.use('/', require('./routes/index'));

const start = async () => {
  try {
    await connectDB(process.env.MONGODB_URI);
    app.listen(port, () => {
      console.log(`Server is listening on port ${port}...`);
      console.log(`Connected to MongoDB Atlas!`);
    });
  } catch (error) {
    console.error('Failed to connect to the database or start the server:', error);
  }
};

start();